version: "3"

services:

    shopware:
      image: dockware/play:latest
      container_name: shopware
      ports:
         - "80:80"
         - "443:443"
         - "3306:3306"
      networks:
         - web

networks:
  web:
    external: false
